@admintoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc2Yzc3ZDY5ODg3YTlmMzRiZGE3N2EiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzM1OTI4NzY1fQ.or7l-fiwd36EVvePUXGObfk8OmesFJRDCjE8Eo0j3Es
@biztoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc2Yzc3ZDY5ODg3YTlmMzRiZGE3N2IiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1OTI4Nzk2fQ.yriW04iwoQTx04HCghE2t7xZK5V1hUg829wfbu3hYYs
@normaltoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc3YmVmMzU3OTliNGExNDdjZmYzZGUiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTczNTkyOTM2Mn0.F-yvTQ3WJVwbuDq43fqWaT2n5g5lJtZZ7jJEniYSY8c

@local=http://localhost:4000

###

POST {{local}}/api/cards
x-auth-token: {{biztoken}}
Content-Type: application/json

{
    "title": "Saul Goodmen",
    "subtitle": "breaking bad",
    "description": "Better Call Saul!",
    "phone": "050120134",
    "email": "jesse.email.com",
    "web": "https://jsonplaceholder.typicode.com/",
    "image": {
        "url": "https://blog.stoplight.io/wp-content/uploads/2023/11/20190403-JSON-Generator-for-Mock-API-Data.png",
        "alt": "api"
    },
    "address": {
        "state": "new mexico",
        "country": "united states",
        "city": "alberququie",
        "street": "nowherestr",
        "houseNumber": 10,
        "zip": "23"
    }
}

###

GET {{local}}/api/cards

###

GET {{local}}/api/cards/my-cards
x-auth-token: {{biztoken}}

###

GET {{local}}/api/cards/67782ed3a4f8778d79cddceb

###

PUT {{local}}/api/cards/67782ed3a4f8778d79cddceb
x-auth-token: {{biztoken}}
Content-Type: application/json

{
    "title": "busy",
    "subtitle": "the",
    "description": "business",
    "phone": "050120134",
    "email": "test.email.com",
    "web": "https://jsonplaceholder.typicode.com/",
    "image": {
        "url": "https://blog.stoplight.io/wp-content/uploads/2023/11/20190403-JSON-Generator-for-Mock-API-Data.png",
        "alt": "api"
    },
    "address": {
        "state": "new york",
        "country": "united states",
        "city": "manhaten",
        "street": "nowherestr",
        "houseNumber": 10,
        "zip": "23"
    }
}

###

DELETE {{local}}/api/cards/67782ed3a4f8778d79cddceb
x-auth-token: {{biztoken}}

###

PATCH {{local}}/api/cards/6779238ba4f8778d79cddd1f
x-auth-token: {{admintoken}}

###

PATCH {{local}}/api/cards/update/6779238ba4f8778d79cddd1f
x-auth-token: {{admintoken}}