@biztoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZkNzAyNjJhYWMzMTM1OTNjMjAxODgiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1MjkzMzY5fQ.YrDkgP6GWsR8OS8kvBRzCeC7bemF-FQBCGEXQ60Itnc
@admintoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZjMDMwODQ4NDE4MmJhOWNkYzMzNDAiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzUyOTk0NjZ9.RohlcqrTl6tMxUAm3ZeYYN_OOQ1CvP8T8z_oI43KfxI

@otherbiztoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZmZWVmODkzNGRlN2M2MTY1N2FhZWQiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1Mzg4OTQ3fQ.GeIE0PwYO5LLBjveJ0IXU2rXF90VoSeMvYzZDMsEwyw

@normaltoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZmZWVkODkzNGRlN2M2MTY1N2FhZWEiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTczNTYzMTc0Nn0.VG7akF0U5EjBI7W8y9-vCesIJH5YGmF5jhZe_B8SIHA

@local=http://localhost:4000

###

POST {{local}}/api/cards
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZkNmZiYjJhYWMzMTM1OTNjMjAxODIiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1NjMyMDU5fQ.5kHAi1T71Z4YZxtV0tamddzwD7NZ_2gupkFlqUE68SY
Content-Type: application/json

{
    "title": "Walter White",
    "subtitle": "breaking bad",
    "description": "High School Chemistiry teacher",
    "phone": "050120134",
    "email": "saul.email.com",
    "web": "https://jsonplaceholder.typicode.com/",
    "image": {
        "url": "https://blog.stoplight.io/wp-content/uploads/2023/11/20190403-JSON-Generator-for-Mock-API-Data.png",
        "alt": "api"
    },
    "address": {
        "state": "new mexico",
        "country": "united states",
        "city": "alberququie",
        "street": "nowherestr",
        "houseNumber": 10,
        "zip": "23"
    }
}

###

GET {{local}}/api/cards

###

GET {{local}}/api/cards/my-cards
x-auth-token: {{biztoken}}

###

GET {{local}}/api/cards/676e820ed77c6c13537e2368

###

PUT {{local}}/api/cards/67739fb8eb5e3a9d8db7071e
x-auth-token: {{otherbiztoken}}
Content-Type: application/json

{
    "title": "busy",
    "subtitle": "the",
    "description": "business",
    "phone": "050120134",
    "email": "test.email.com",
    "web": "https://jsonplaceholder.typicode.com/",
    "image": {
        "url": "https://blog.stoplight.io/wp-content/uploads/2023/11/20190403-JSON-Generator-for-Mock-API-Data.png",
        "alt": "api"
    },
    "address": {
        "state": "new york",
        "country": "united states",
        "city": "manhaten",
        "street": "nowherestr",
        "houseNumber": 10,
        "zip": "23"
    }
}

###

DELETE {{local}}/api/cards/6773a510ae5bf62fc65a205d
x-auth-token: {{otherbiztoken}}

###

PATCH {{local}}/api/cards/67700bfe659c2d0f392316b2
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZmZWVmODkzNGRlN2M2MTY1N2FhZWQiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1Mzk5NDkyfQ.pYbB02Dvhlp3uJK5Qp-Bkw27bfFK8-MzleB_j_SYmn8