@local=http://localhost:4000
@admintoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZjMDMwODQ4NDE4MmJhOWNkYzMzNDAiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzUyMjY4NjR9.HR58ejjrMBFaUFobOHwShEFrKv9YjynLYbXdmtwOEQ4
@biztoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZkNzAyNjJhYWMzMTM1OTNjMjAxODgiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1MjI1NTIwfQ.d1LoSCJLv9hcsHU0H9gXdy7JngZgy0RMz1qGAQe2qh0
@normaltoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZkNDZmMGEwYTIyNzdjMmE5NGJlYTgiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1MjI1MTM2fQ.Vygn-jAoNFcXJoeyd4p506CINPUM0KRKEurLm6c3mWA

###
POST {{local}}/api/users
Content-Type: application/json

{
    "name": {
        "first": "john",
        "middle": "normal",
        "last": "Doe"
    },
    "isBusiness": "true",
    "phone": "050502120",
    "email": "john@email.com",
    "address": {
        "country": "Israel",
        "city": "Haifa",
        "street": "this street",
        "houseNumber": 1
    },
    "password": "Aa123456",
    "image": {
        "url": "https://i.pinimg.com/236x/33/d0/a2/33d0a23afdc4112ae4c984cb39dcad22.jpg",
        "alt": "IT WAS YOU!"
    }
}


###

POST {{local}}/api/auth/
Content-Type: application/json

{
    "email": "normal@email.com",
    "password": "Aa123456"
}

###

GET {{local}}/api/users/67739d9c271d2d1cb6972da5
x-auth-token: {{normaltoken}}
###

GET {{local}}/api/users/allUsers
x-auth-token: {{admintoken}}

###

PUT {{local}}/api/users/67739d9c271d2d1cb6972da5
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzczOWQ5YzI3MWQyZDFjYjY5NzJkYTUiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1NjMwMzYyfQ.u2I_jWs2H-hnE4abWCleZR4DZ_5EANxf8P2yzdIEPIs
Content-Type: application/json

{
      "name": {
        "first": "johnny",
        "middle": "normal",
        "last": "Doe"
    },
    "isBusiness": "true",
    "phone": "050502120",
    "email": "john@email.com",
    "address": {
        "country": "Israel",
        "city": "Haifa",
        "street": "this street",
        "houseNumber": 1
    },
    "password": "Aa123456",
    "image": {
        "url": "https://i.pinimg.com/236x/33/d0/a2/33d0a23afdc4112ae4c984cb39dcad22.jpg",
        "alt": "IT WAS YOU!!!!!!!"
    }
}

###

DELETE {{local}}/api/users/67739d9c271d2d1cb6972da5
x-auth-token: {{admintoken}}

###
PATCH {{local}}/api/users/67739d64271d2d1cb6972da2
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzczOWQ2NDI3MWQyZDFjYjY5NzJkYTIiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1NjMwNTgzfQ.7lftJ-em8nobPzsFekadfOw3xhwf5bqV4A5WUqlEgM4