@local=http://localhost:4000
@admintoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc2Yzc3ZDY5ODg3YTlmMzRiZGE3N2EiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzM1OTI4NzY1fQ.or7l-fiwd36EVvePUXGObfk8OmesFJRDCjE8Eo0j3Es
@biztoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc2Yzc3ZDY5ODg3YTlmMzRiZGE3N2IiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM1OTI4Nzk2fQ.yriW04iwoQTx04HCghE2t7xZK5V1hUg829wfbu3hYYs
@normaltoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc5Njg4NDAwYjA1MGI1ZDkzN2NiODkiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTczNjAwOTkzOX0.xlHHNGi3Tpi2kZSxGUHAtEZIx7KfikXLtdVTLHzu6fI

###
POST {{local}}/api/users
Content-Type: application/json

{
    "name": {
        "first": "saul",
        "middle": "",
        "last": "goodmen"
    },
    "isBusiness": "false",
    "phone": "050502120",
    "email": "false@email.com",
    "address": {
        "country": "Israel",
        "city": "Haifa",
        "street": "this street",
        "houseNumber": 2,
        "zip": "23"
    },
    "password": "Aa123456",
    "image": {
        "url": "https://i.pinimg.com/236x/33/d0/a2/33d0a23afdc4112ae4c984cb39dcad22.jpg",
        "alt": "IT WAS YOU!"
    }
}


###

POST {{local}}/api/auth/
Content-Type: application/json

{
    "email": "false@email.com",
    "password": "Aa123456"
}

###

GET {{local}}/api/users/6777bef35799b4a147cff3de
x-auth-token: {{admintoken}}

###
GET {{local}}/api/users/allUsers
x-auth-token: {{biztoken}}

###

PUT {{local}}/api/users/6777bef35799b4a147cff3de
x-auth-token: {{normaltoken}}
Content-Type: application/json

{
      "name": {
        "first": "saulll",
        "middle": "",
        "last": "goodmen"
    },
    "isBusiness": "true",
    "phone": "050502120",
    "email": "saul@email.com",
    "address": {
        "country": "Israel",
        "city": "Haifa",
        "street": "this street",
        "houseNumber": 2,
        "zip": 4
    },
    "image": {
        "url": "https://i.pinimg.com/236x/33/d0/a2/33d0a23afdc4112ae4c984cb39dcad22.jpg",
        "alt": "IT WAS YOU!!!!!!!"
    }
}

###

DELETE {{local}}/api/users/6779688400b050b5d937cb89
x-auth-token: {{admintoken}}

###
PATCH {{local}}/api/users/6777bef35799b4a147cff3de
x-auth-token: {{normaltoken}}