export const initialCards = [
  {
    title: "one",
    subTitle: "one two",
    description: "one two three",
    phone: 4445789,
    email: "one@gmail.com",
    web: "https://www.google.com/",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/en/e/ee/Front_%26_Back_Face_of_iPhone_16_Pro_Max.png",
      alt: "iphone",
    },
    address: {
      state: "",
      country: "USA",
      city: "LA",
      street: "LA city",
      houseNumber: 330,
      zip: 12345,
    },
    bizNumber: 123345,
    userId: "676844a3eaa5432d476822a5",
  },
  {
    title: "two",
    subTitle: "two two",
    description: "one two three",
    phone: 21123125,
    email: "two@gmail.com",
    web: "https://www.google.com/",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/en/e/ee/Front_%26_Back_Face_of_iPhone_16_Pro_Max.png",
      alt: "iphone",
    },
    address: {
      state: "",
      country: "USA",
      city: "LA",
      street: "LA city",
      houseNumber: 330,
      zip: 12345,
    },
    bizNumber: 123345,
    userId: "676844a3eaa5432d476822a5",
  },
  {
    title: "three",
    subTitle: "four five",
    description: "one two three",
    phone: 5465423,
    email: "three@gmail.com",
    web: "https://www.google.com/",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/en/e/ee/Front_%26_Back_Face_of_iPhone_16_Pro_Max.png",
      alt: "iphone",
    },
    address: {
      state: "",
      country: "USA",
      city: "LA",
      street: "LA city",
      houseNumber: 330,
      zip: 12345,
    },
    bizNumber: 123345,
    userId: "676844a3eaa5432d476822a5",
  },
];
